spring.application.name=uberApp

#DB configuration
spring.datasource.url=jdbc:mysql://localhost:3306/uberApp?useSSL=false
spring.datasource.username=root
spring.datasource.password=2003
spring.jpa.hibernate.ddl-auto=create-drop


#smtp config
spring.mail.username=mdswaley075@gmail.com
spring.mail.password=lyxy ckft qeet sfgs
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secretKey = paiosdfqg43j51b4hjbhcafifa87dsf6hk32jhkrj9a7dfhkjhalkasdf97823